apiVersion: v1
description: Official Elastic helm chart for Logstash
home: https://github.com/elastic/helm-charts
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: logstash
version: 7.5.1-oto
appVersion: 7.5.1-oto
sources:
  - https://github.com/otosystems/elastic-helm-charts
icon: https://helm.elastic.co/icons/logstash.png
